### ISSUE TITLE
Create a simple contact form inside the assignment2.html  (see picture below)

### ISSUE THREAD

**Issue by r0nnie-20** [r0nnie-20/IcreatechsStudyHub#26]
**Create a simple contact form**
![Screen Shot 2023-08-04 at 08 02 33](https://github.com/r0nnie-20/IcreatechsStudyHub/assets/109708984/67573c0d-83a6-4106-a8b6-2ddcbc86cc63)

**Comment by Codesloth15** [comment]
i created simple contact form
