### ISSUE TITLE
Formatting and styling: Experiment with different HTML tags to apply some basic formatting and styling to your content. For example, use <strong>, <em>, <b>.

### ISSUE THREAD

**Issue by r0nnie-20** [r0nnie-20/IcreatechsStudyHub#8]

**Comment by MBAbalos** [comment]
Pacheck po kung okay na po about sa html tags. naglagay po  ako ng strong em and u tags. Tas hr tag para po sa hindi masama ang h1 sa list. Thank you po!

**Comment by r0nnie-20** [comment]
Hello po, kindly do the issue again kase po I can't merge this in master branch since there is a conflict

**Comment by MBAbalos** [comment]
Tapos na po. Pacheck nalang po kung okay na po. Thank you !
